site_name: Awesome DevOps
site_url: http://awesome-devops.xyz
site_description: A curated list of awesome DevOps platforms, tools, practices and resources
site_author: Marius Stanca
repo_name: awesome-devops Github
repo_url: http://github.com/wmariuss/awesome-devops
edit_uri: https://github.com/wmariuss/awesome-devops/blob/master/README.md

# Copyright
copyright: "Copyright &copy; Awesome DevOps Community"

# Theme
theme:
  name: material
  language: en
  locale: en
  font:
    text: Roboto Slab
    code: Source Code Pro
  palette:
    primary: black
    accent: blue
  icon:
    logo: logo
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - toc.follow

# Extra
extra:
  feature:
    tabs: true
  social:
    - icon: fontawesome/solid/globe
      link: http://marius.xyz
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wmariuss
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wmariuss
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wmariuss

extra_css:
  - stylesheets/syntax.css
  - stylesheets/fonts.css

extra_javascript:
  - javascripts/syntax.js

# Plugins
plugins:
  - search:
      lang: en

# Navigator
nav:
  - Welcome: "index.md"
  - List: "list.md"
  - Contribution: "contribution.md"

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
